.eslintrc.json, package-lock.json, package.json
eslint config added (used dbwebb standard config)  
added the npm package pre-commit to handle the git hook
=> uppdated eslint conf and added hook

API_DOC.md, README.md, index.js, router/objects.js, src/dbWrapper.js, src/getObjectInformation.js
This adds API routes for objects. They are all documented in the `API_DOC.md`  
This closes #9
=> API routes for objects

config/dbConfig.example.js, src/dbWrapper.js
The backend now fetch the database name to be used from the config.
This closes #12
=> Add database name to config

index.js, middleware/validateInput.js, router/objects.js
This branch adds input validation for both query parameters and url parameters
Closes #6
=> Input validation

setup/setup.sh
Puts in the database user inside the users database so the user ca log into the database after setup is done.
=> fixed permissions for login to mongodb

config/dbConfig.example.js, router/objects.js, src/dbWrapper.js, src/getObjectInformation.js
This fixes the server authentication with the mongodb database. Closes critical issue #28
=> Server authenticate to db

index.js
This PR closes issue #30 by setting the header to allow all API connections.
=> Fix cors origin

.gitignore, API_DOC.md, config/emailConfig.example.js, index.js, middleware/authValidator.js, package-lock.json, package.json, router/admin.js, router/login.js, setup/createCollections.js, src/dbWrapper.js, src/jwtAuthentication.js, src/loginHandler.js, src/smtpMailman.js
This adds a complete user login system and accounts with both users and admins. Admins can create new accounts. Closes #33 #36 #37 #38 #39 #40 #41 #44
=> User login system

README.md
add short description about email settings.
=> add note about email setup

router/login.js
Adds return value "username", Closes #54
=> add return username on sucessful login

API_DOC.md, src/handleProjects.js
Insert project can now take default values as a parameter.
=> Handle project update

API_DOC.md, index.js, router/user.js, src/userHandler.js
add route to fetch id and username for all users. Requires valid token but not admin status. Closes #52
=> add /user/all route

setup/insertObjects.js, src/handleProjects.js
- Object data is updated
- New object are added (pumps and pumpstation)
- Old unused object are removed
closes issue #60
=> updated current products data and added new products

src/getObjectInformation.js
Changed from type to type[0] in getObj.
=> changed type to type[0]

index.js, router/admin.js, src/jwtAuthentication.js, src/loginHandler.js
Fixes unhandled promise rejections, adds more verbose errors for email parsing, fixed header for allowing client to send 'Content-Type', Added base code for renewing tokens - will be implemented in a new branch.  
Closes #46, Closes #49, Closes #70
=> Optimize handling

setup/insertObjects.js
kompos 61, 81, 82
not kompost 61,81,92
=> Fixed insert of kompost 61, 81, 92

API_DOC.md, router/objects.js, router/projects.js, src/getObjectInformation.js, src/handleProjects.js
=> Object icons in database

index.js
=> Set max image size

API_DOC.md, router/objects.js, router/projects.js, src/getObjectInformation.js, src/handleProjects.js
=> Local global products

setup/insertObjects.js
Updated pump names to fix issue where pumpstations refer to other pump names
=> Removed whitespaces in pump names

router/login.js, setup/createAdminAccount.js
Closes issue: #45 
Removed signup ability from routes and moved to a script in the folder setup (The script is not included in setup.sh).
=> Remove signup

package.json, src/loginHandler.js
Email validator is broken and is now removed.
=> removed depricated email validator

.eslintignore, package-lock.json
**Changes**:
- Updated installed NPM packages 
Closes #110
=> Updated npm

package-lock.json, package.json
**Changes**:
- Added forgotten NPM packet promts
Closes no existing issues
=> added forgotten npm packages

src/adminFunctions.js
When a request was declined the object disappeared into space.
Now fixed.
=> Fixed decline global request bug

API_DOC.md, router/user.js
Adding this new route will mean we don't have to rely on other routes for validating a users login
=> added verify login route
